name: sdsl-lite C++ CI

on: [push]

jobs:

  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: checkout submodules
      run: git submodule update --init --recursive

    - name: install dependencies
      run: |
        sudo apt-get install g++-9
    - name: install sdsl-lite
      run: |
        export CC=$(which gcc-9)
        export CXX=$(which g++-9)
        ./install.sh $(pwd)
    - name: test sdsl-lite
      run: |
        export CC=$(which gcc-9)
        export CXX=$(which g++-9)
        mkdir -p build && cd build && make test-sdsl

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: checkout submodules
      run: git submodule update --init --recursive

    - name: install sdsl-lite
      run: ./install.sh $(pwd)

    - name: test sdsl-lite
      run: mkdir -p build && cd build && make test-sdsl
